enum MACHINE_STATES {
    MACHINE_STATE_EMPTY = 0,
    MACHINE_STATE_NEW = 1,

    MACHINE_STATE_PROVISIONING_BT_CONNECTED = 101,
    MACHINE_STATE_PROVISIONING_BT_TRANSFER = 102,
    MACHINE_STATE_PROVISIONING_WIFI_CONNECTING = 103,
    MACHINE_STATE_PROVISIONING_MQTT_CONNECTING = 104,
    MACHINE_STATE_PROVISIONING_CONNECTED = 105,

    MACHINE_STATE_TRAINING_READY = 201,
    MACHINE_STATE_TRAINING_DOWNLOADING = 202,
    MACHINE_STATE_TRAINING_COMPLETE = 203,
    MACHINE_STATE_TRAINING_RECORD_READY = 204,
    MACHINE_STATE_TRAINING_RECORDING = 205,
    MACHINE_STATE_TRAINING_RECORDED = 206,

    MACHINE_STATE_ACTIVE_DUTY_CONNECTED = 301,
    MACHINE_STATE_ACTIVE_DUTY_RUNNING_CMD = 302,

    MACHINE_STATE_RESET_BUTTON_HOLD = 401,
    MACHINE_STATE_RESET_CLEAR_WIFI = 402,
    MACHINE_STATE_RESET_CLEAR_WIFI_MQTT = 403,
    MACHINE_STATE_RESET_CLEAR_WIFI_MQTT_TRAINING = 404
};

error_t start_state_machine();
int get_current_state_from_ram();
error_t set_state_machine_state(const int32_t);
